import { useEffect, useMemo, useState } from "react";
import { FormProvider, useForm } from "react-hook-form";
import { FileText, Pencil, Plus, Search, X } from "lucide-react";
import { api } from "../api";
import { FieldInput, FieldSelect, FieldTextarea } from "../components/fields";
import type { Supplier, SupplierInvoice } from "../types";

const money = (cents: number) => new Intl.NumberFormat("es", { style: "currency", currency: "CUP" }).format(cents / 100);
export function SupplierInvoicesPage() {
  const [invoices, setInvoices] = useState<SupplierInvoice[]>([]); const [suppliers, setSuppliers] = useState<Supplier[]>([]);
  const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<SupplierInvoice | null>(null); const [error, setError] = useState("");
  const methods = useForm<{ supplierId: string; invoiceNumber: string; invoiceDate: string; totalAmount: number; notes: string }>({ defaultValues: { supplierId: "", invoiceNumber: "", invoiceDate: new Date().toISOString().slice(0, 10), totalAmount: 0, notes: "" } });
  async function load() { const [i, s] = await Promise.all([api.supplierInvoices(), api.suppliers()]); setInvoices(i.invoices); setSuppliers(s.suppliers); }
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => invoices.filter((i) => `${i.invoiceNumber} ${i.supplierName}`.toLowerCase().includes(query.toLowerCase())), [invoices, query]);
  function showForm(invoice?: SupplierInvoice) {
    setEditing(invoice ?? null); setError("");
    methods.reset(invoice ? { supplierId: invoice.supplierId, invoiceNumber: invoice.invoiceNumber,
      invoiceDate: invoice.invoiceDate, totalAmount: invoice.totalAmountCents / 100, notes: invoice.notes ?? "" }
      : { supplierId: "", invoiceNumber: "", invoiceDate: new Date().toISOString().slice(0, 10), totalAmount: 0, notes: "" });
    setOpen(true);
  }
  async function submit(values: { supplierId: string; invoiceNumber: string; invoiceDate: string; totalAmount: number; notes: string }) { setError(""); try { const input = { supplierId: values.supplierId, invoiceNumber: values.invoiceNumber, invoiceDate: values.invoiceDate, totalAmountCents: Math.round(values.totalAmount * 100), notes: values.notes }; editing ? await api.updateSupplierInvoice(editing.id, input) : await api.createSupplierInvoice(input); setOpen(false); setEditing(null); methods.reset(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo guardar la factura"); } }
  return <section><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-black uppercase tracking-wider text-emerald-700">Compras</p><h1 className="mt-1 text-3xl font-black">Facturas de proveedores</h1><p className="mt-2 text-slate-500">Documentos de compra vinculables con los lotes recibidos.</p></div><button disabled={suppliers.length === 0} onClick={() => showForm()} className="flex items-center justify-center gap-2 rounded-2xl bg-emerald-700 px-5 py-3 font-black text-white disabled:opacity-40"><Plus size={18} /> Nueva factura</button></div>
    {suppliers.length === 0 && <p className="mt-5 rounded-2xl bg-amber-50 p-4 text-sm font-bold text-amber-800">Primero debes registrar al menos un proveedor.</p>}
    <div className="mt-6 rounded-3xl bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-slate-100 p-4"><Search className="text-slate-400" size={20} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por proveedor o número" className="w-full bg-transparent py-2 outline-none" /></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-4">Factura</th><th>Proveedor</th><th>Fecha</th><th>Total</th><th>Lotes</th><th></th></tr></thead><tbody>{visible.map((invoice) => <tr key={invoice.id} className="border-t border-slate-100"><td className="px-5 py-4 font-black">{invoice.invoiceNumber}</td><td className="font-bold">{invoice.supplierName}</td><td>{invoice.invoiceDate}</td><td className="font-black">{money(invoice.totalAmountCents)}</td><td>{invoice.batchCount}</td><td className="px-5 text-right"><button onClick={() => showForm(invoice)} className="rounded-xl border border-slate-200 p-2 hover:bg-slate-50" aria-label={`Editar factura ${invoice.invoiceNumber}`}><Pencil size={16} /></button></td></tr>)}</tbody></table></div>{visible.length === 0 && <div className="grid place-items-center p-14 text-slate-400"><FileText size={40} /><p className="mt-3 font-bold">No hay facturas para mostrar.</p></div>}</div>
    {open && <div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/45 p-4"><FormProvider {...methods}><form onSubmit={methods.handleSubmit(submit)} className="w-full max-w-lg rounded-[2rem] bg-white p-7"><div className="flex justify-between"><h2 className="text-2xl font-black">{editing ? "Editar factura" : "Nueva factura"}</h2><button type="button" onClick={() => setOpen(false)}><X /></button></div><div className="mt-6 grid gap-4"><FieldSelect label="Proveedor" placeholder="Selecciona un proveedor" isSearchable searchPlaceholder="Buscar proveedor..." options={suppliers.map((s) => ({ value: s.id, label: s.name }))} getSearchFilter={(search, option) => option.label.toLowerCase().includes(search.trim().toLowerCase())} register={methods.register("supplierId", { required: "Selecciona un proveedor" })} error={methods.formState.errors.supplierId} /><FieldInput label="Número de factura" register={methods.register("invoiceNumber", { required: "El número es obligatorio" })} error={methods.formState.errors.invoiceNumber} /><FieldInput label="Fecha" type="date" register={methods.register("invoiceDate", { required: "La fecha es obligatoria" })} error={methods.formState.errors.invoiceDate} /><FieldInput label="Importe total" type="number" min="0" step="0.01" register={methods.register("totalAmount", { valueAsNumber: true, required: "El importe es obligatorio", min: { value: 0, message: "El importe no puede ser negativo" } })} error={methods.formState.errors.totalAmount} /><FieldTextarea label="Notas" rows={3} register={methods.register("notes")} /></div>{error && <p className="mt-4 rounded-2xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="px-4 font-black text-slate-500">Cancelar</button><button disabled={methods.formState.isSubmitting} className="rounded-xl bg-emerald-700 px-5 py-2.5 font-black text-white">{editing ? "Guardar cambios" : "Guardar"}</button></div></form></FormProvider></div>}
  </section>;
}
